name: Build and Push Docker Image (Dev)

on:
  push:
    branches:
      - dev

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/number-guess-game:dev-${{ github.sha }} .

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/number-guess-game:dev-${{ github.sha }}

      - name: Tag latest dev image
        run: |
          docker tag ${{ secrets.DOCKER_HUB_USERNAME }}/number-guess-game:dev-${{ github.sha }} ${{ secrets.DOCKER_HUB_USERNAME }}/number-guess-game:dev-latest
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/number-guess-game:dev-latest
