name: Build and Push Docker Image (QA)

on:
  push:
    branches:
      - qa

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/number-guess-game:qa-${{ github.sha }} .

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/number-guess-game:qa-${{ github.sha }}

      - name: Tag latest qa image
        run: |
          docker tag ${{ secrets.DOCKER_HUB_USERNAME }}/number-guess-game:qa-${{ github.sha }} ${{ secrets.DOCKER_HUB_USERNAME }}/number-guess-game:qa-latest
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/number-guess-game:qa-latest
